### ISSUE TITLE
Reimplementation of known examples from other packages

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-train#11]
Following issue #5 it would be interesting to see if we can already reimplement a couple of well-known examples from other packages, for instance Keras?

**Comment by kpu** [comment]
We have MNIST, but not anything convolutional or CIFAR.  These are important to have in papers comparing NMT behavior vs other tasks.

**Comment by emjotde** [comment]
Tomasz is working on convolutions in convnet branch. This will soon be added. I close this issue as it was sort of inactive. I would actually plan to reimplement both, the facebook convnet and the google transformer stuff.

**Comment by emjotde** [comment]
Maybe it would make more sense to have specific issues for concrete models. This one is about all and nothing.

**Comment by emjotde** [comment]
So, I am closing this one again. And if you have needs for a specific model or an interesting idea, open a new issue for that.
