### ISSUE TITLE
Merge with AmuNMT

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-train#30]
A shallow merge for now. Amun and Marian communicate through the model file, which should be ok as long as we do not have a Marian scorer in Amun. 

What should we do with the repos? New repo? New organization? New name?

**Comment by hieuhoang** [comment]
An organisation definitely. 

Amun should be Amun, or AmuNMT consistently otherwise it causes confusion. Amun is prob better.

Can you git pull when merging so that the git history is retained. Need to convince the bosses I'm doing some work and not sitting on a beach drinking pina colada

**Comment by emjotde** [comment]
Sure. I have this domain, "unrolled.ai". Would that be an organization name?

**Comment by hieuhoang** [comment]
might as well

**Comment by hieuhoang** [comment]
might be best to just rename amun. Or somehow bring the issues and pull request page to the new repo. The discussions on there is useful for the long term

**Comment by hieuhoang** [comment]
rename -> move

**Comment by hieuhoang** [comment]
https://github.com/IQAndreas/github-issues-import

**Comment by emjotde** [comment]
At first I will just transfer the ownership of the repos, everything is being move then. Maybe I will keep amun and marian apart for now.

**Comment by tomekd** [comment]
suggestion: amun and marian uses the same 3rd parties code: spdlog, cnpy, etc. I think it's worth to make it common. I mean to have three directories: ``amun``, ``marian``, ``3rd_party``.

**Comment by emjotde** [comment]
@tomekd yes, but let's wait with this a bit.
