### ISSUE TITLE
Unit and regression tests

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-train#44]
Should be able to tell if code is working without waiting an hour.  

Unit tests: small graphs exercising only parts of the code?  

Regression tests: save some checkpoints of small canned systems.  Start from these checkpoints and verify the outcome is about the same.

**Comment by emjotde** [comment]
Can you delegate on your minions ?

**Comment by snukky** [comment]
I added a unit test framework with example unit tests (see 3f51d65, 085754c).
There is also the [regression-testing branch](https://github.com/marian-nmt/marian-train/commits/regression-testing) but it seems to be outdated.

**Comment by emjotde** [comment]
Moving discussion to issue https://github.com/marian-nmt/marian/issues/76
