### ISSUE TITLE
Segfault after the program runs for a while

### ISSUE THREAD

**Issue by afaji** [marian-nmt/marian-train#45]
Hi

I got segfault after the code runs for a couple hours. Not sure why. This is based on a code pulled a week ago. I'm pulling the new one to see if the issue still there.

```
[2017-03-22 11:00:52] Ep. 4 : Up. 21900 : Sen. 281600 : Cost 27.39 : Time 49.85s : 2981.00 words/s
[2017-03-22 11:01:42] Ep. 4 : Up. 22000 : Sen. 288000 : Cost 26.35 : Time 49.64s : 2842.05 words/s
[2017-03-22 11:02:33] Ep. 4 : Up. 22100 : Sen. 294400 : Cost 27.27 : Time 50.95s : 2881.92 words/s
GPUassert: an illegal memory access was encountered /home/alfikri/ori/marian/src/tensors/tensor.cu 83
GPUassert: driver shutting down /home/alfikri/ori/marian/src/tensors/tensor.cu 46
GPUassert: driver shutting down /home/alfikri/ori/marian/src/tensors/tensor.cu 46
GPUassert: driver shutting down /home/alfikri/ori/marian/src/kernels/tensor_operators.cu 603
GPUassert: an illegal memory access was encountered /home/alfikri/ori/marian/src/kernels/tensor_operators.cu 608
*** Error in `./marian': double free or corruption (!prev): 0x000055821fb66320 ***
Segmentation fault (core dumped)
```

**Comment by emjotde** [comment]
Hi,
That looks more like a driver error to me? What machine is this? Also does this happen regularly, only once, only with your branch? Too little information to guess anything.

**Comment by afaji** [comment]
this is from master, original code without modifying anything.
Happened once, just today.

**Comment by emjotde** [comment]
Hm, difficult to say. What's the driver version? On some machines the nvidia drivers are highly unstable, not something we can fix really.

**Comment by afaji** [comment]
Tesla M60

Actually, just happened again right now, with freshly pulled code:
```
[2017-03-22 16:49:00] Ep. 1 : Up. 5600 : Sen. 358400 : Cost 56.34 : Time 48.07s : 3026.32 words/s
[2017-03-22 16:49:52] Ep. 1 : Up. 5700 : Sen. 364800 : Cost 55.40 : Time 51.16s : 2809.11 words/s
[2017-03-22 16:50:42] Ep. 1 : Up. 5800 : Sen. 371200 : Cost 56.01 : Time 50.92s : 2893.21 words/s
GPUassert: an illegal memory access was encountered /home/alfikri/ori/marian/src/kernels/tensor_operators.cu 567
GPUassert: an illegal memory access was encountered /home/alfikri/ori/marian/src/tensors/tensor.cu 46
Segmentation fault (core dumped)
```

**Comment by emjotde** [comment]
Can you reset the machine? Maybe the driver went out of whack.

W dniu 22.03.2017 o 17:57, afaji pisze:

**Comment by afaji** [comment]
Still happened after reset.
I just deallocate and re-start the azure server, not sure if that counts as resetting the machine.

```
[2017-03-22 18:33:09] Ep. 2 : Up. 7100 : Sen. 81408 : Cost 47.13 : Time 49.01s : 3035.36 words/s
[2017-03-22 18:33:53] Ep. 2 : Up. 7200 : Sen. 87808 : Cost 43.82 : Time 44.38s : 3113.88 words/s
[2017-03-22 18:34:46] Ep. 2 : Up. 7300 : Sen. 94208 : Cost 48.74 : Time 52.93s : 2899.93 words/s
GPUassert: an illegal memory access was encountered /home/alfikri/ori/marian/src/kernels/tensor_operators.cu 567
GPUassert: an illegal memory access was encountered /home/alfikri/ori/marian/src/tensors/tensor.cu 46
Segmentation fault (core dumped)
```

So this is 3 errors in 3 attempts.

**Comment by emjotde** [comment]
OK, very weird. Which driver version is nvidia-smi reporting?

Can you make the data and a config with your parameters avalable for 
download?

W dniu 23.03.2017 o 08:37, afaji pisze:

**Comment by afaji** [comment]
Driver version: 375.39 

config: `./marian -t corpus.ro corpus.en -d 0 1 2 3 --disp-freq=100 --layer-normalization --log=data_baseline.txt`

data: 
I ran the this [wmt script](https://github.com/rsennrich/wmt16-scripts/blob/master/sample/download_files.sh) and used corpus.ro and corpus.en

**Comment by emjotde** [comment]
I have been having problems with those new driver version, especially with this version (weird erros, random freezes), and downgraded to 367.48 on all my machines. This made all errors go away. You can try this and I can experiment with the data in the meantime.

**Comment by emjotde** [comment]
You did not do any preprocessing? Notice that the data is not even tokenized. But I guess it might be empty lines or something, so maybe a good test. Good chance this is a case of garbage in/garbage out.

**Comment by afaji** [comment]
I always thought Marian did the preprocessing...

but I don't think unprocessed data causes the error. You might get a crappy result, though.

Now that I retry with preprocessed data, I found something interesting:
```
[2017-03-23 09:22:39] [config] train-sets:
[2017-03-23 09:22:39] [config]   - corpusPrep.ro
[2017-03-23 09:22:39] [config]   - corpusPrep.en
[2017-03-23 09:22:39] [config] type: dl4mt
[2017-03-23 09:22:39] [config] valid-freq: 10000
[2017-03-23 09:22:39] [config] valid-metrics:
[2017-03-23 09:22:39] [config]   - cross-entropy
[2017-03-23 09:22:39] [config] vocabs:
[2017-03-23 09:22:39] [config]   - corpus.ro.yml
[2017-03-23 09:22:39] [config]   - corpus.en.yml
[2017-03-23 09:22:39] [config] workspace: 2048
```

see that vocab file is corpus.ro.yml, even though my trainfile is corpusPrep.ro. In fact no matter what my train file name is, the vocab is always corpus.ro.yml. Is this intended? Maybe we load wrong vocab thus causing the crash.

**Comment by afaji** [comment]
I see..

so that's not the issue. Currently training the preprocessed files.

**Comment by kpu** [comment]
@afaji can you make a minimal test case (tokenized or not) that causes the segfault then check it in, intentionally breaking the build?

**Comment by emjotde** [comment]
I am running it now on the unprocessed data. So far no problems. I still suspect it's the driver version.

**Comment by emjotde** [comment]
So, six full epochs. no problem. You might want to check downgrading that driver...

**Comment by emjotde** [comment]
Two times 10 epochs, no segfault.
