### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by mjpost** [marian-nmt/marian-train#54]
Under CentOS 7.3.1611 with

- GCC 4.9.3
- Boost 1.53.0
- cmake 3.6.3

I had to make two changes to get marian to compile:

-  I had to add this line near the top of `CMakeLists.txt`:

       set(THREADS_PREFER_PTHREAD_FLAG TRUE)

-  I had to change `Ptr<Reporter> reporter_` (in `src/training/graph_group.h`) to be public in order to get the code to compile. (Obviously there is a more principled way to do this, but this at least gets things running).

**Comment by emjotde** [comment]
Hi,
Can do 1), refuse to do 2) . The second issue seems to be a bug in gcc. I could not reproduce that with multiple compilers and logically it makes no sense either. That variable should totally work while being protected. @phikoehn ran into the same problem, but it seems not to be a C++ error. I think it goes away with a different compiler?

**Comment by mjpost** [comment]
Maybe don't waste too much time on (2), I agree it doesn't make a lot of sense. I'll try with another compiler but in the meantime making it public is an easy local fix.

**Comment by emjotde** [comment]
There's been a lot of changes recently in that area of code. Can you check if the issue still persists?
