### ISSUE TITLE
Check on BatchGenerator rewinding

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-train#57]
There might be a couple of bugs in border-line situations:
* corpus smaller than batch size
* rewinding seems to cause weird sentence counting

Might be worth it to do a couple of sanity checks.

**Comment by snukky** [comment]
I checked several configurations of mini/maxi batches and corpora sizes. The number of sentences displayed at the beginning of each epoch which differs from `number of updates * mini-batch size` with dynamic batching is expected.

I fixed a bug with empty corpora.
