### ISSUE TITLE
Jenkins for marian-train not triggered

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-train#65]
Maybe because of the name change? Jenkins compilation tasks are not being triggered for `marian-train`.

**Comment by snukky** [comment]
Jenkins for _marian-train_ seems to work again.

**Comment by emjotde** [comment]
I am getting a 404 error when checking the "build passing" icon.

**Comment by tomekd** [comment]
confirmed. @snukky changed job name on Jenkins. I'm updating README now and then should work.

**Comment by tomekd** [comment]
Fixed.

**Comment by emjotde** [comment]
Looks good. Thanks to both of you.
