### ISSUE TITLE
Add support for reading in external embedding vectors

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-train#69]
A new parameter intializer that can read for instance word2vec text format for embeddings vectors and add options for src and target embeddings.

**Comment by geovedi** [comment]
since embedding branch has been merged into master, could it be useful to have feature that can freeze certain layers (at least `Wemb` and `Wemb_dec`?) in order to speed up training or maybe helpful in transfer learning task?

**Comment by emjotde** [comment]
Working on this right now.

**Comment by emjotde** [comment]
Done. You can now fix src and target embeddings with `--embedding-fix-src` and `--embedding-fix-trg`. This is independent from the `--embedding-vectors` and can be used to fix the embeddings from a reloaded model. 

Keep this open because the script for word2vec conversion needs some more work.

**Comment by geovedi** [comment]
running a training process for back translation now by reusing and swapping the embeddings from previously trained model (i submitted PR for embedding extractor). 

there's speed improvement on word/s most likely due to fix embedding but not by large margin.

previous run:

```
[2017-07-04 03:39:09] Ep. 1 : Up. 1000 : Sen. 192860 : Cost 346.49 : Time 767.07s : 8276.17 words/s
[2017-07-04 03:51:50] Ep. 1 : Up. 2000 : Sen. 385946 : Cost 284.11 : Time 761.10s : 8336.49 words/s
[2017-07-04 04:04:33] Ep. 1 : Up. 3000 : Sen. 578951 : Cost 250.54 : Time 763.04s : 8329.70 words/s
...
```

current run:

```
[2017-07-04 06:23:46] Ep. 1 : Up. 1000 : Sen. 192353 : Cost 344.09 : Time 753.47s : 8411.36 words/s
[2017-07-04 06:36:12] Ep. 1 : Up. 2000 : Sen. 385240 : Cost 296.33 : Time 745.81s : 8495.59 words/s
[2017-07-04 06:48:41] Ep. 1 : Up. 3000 : Sen. 578013 : Cost 274.50 : Time 749.21s : 8483.73 words/s
...
```

**Comment by emjotde** [comment]
It's not really meant for improving speed anyway.

**Comment by emjotde** [comment]
However, I just experimented with the `--embedding-vectors ...` option in combination with `--tied-embeddings`. There is some insane increased convergence during the first iterations.

**Comment by geovedi** [comment]
is that a good sign? haven't try s2s model again as i'm currently focus on cpu deployment. maybe next week.

**Comment by emjotde** [comment]
Cannot say anything before full experiment, but looks good. This will also work with `--type amun`. I need to remove the `(s2s)`.

**Comment by geovedi** [comment]
restarted the training to enable `tied-embeddings`.  the cost is slow to decrease, is that normal?

```
[2017-07-04 07:46:53] Ep. 1 : Up. 1000 : Sen. 193346 : Cost 430.11 : Time 744.48s : 8543.53 words/s
[2017-07-04 07:59:10] Ep. 1 : Up. 2000 : Sen. 385242 : Cost 411.45 : Time 737.02s : 8568.55 words/s
[2017-07-04 08:11:30] Ep. 1 : Up. 3000 : Sen. 577528 : Cost 404.44 : Time 739.26s : 8576.62 words/s
```

**Comment by emjotde** [comment]
That looks broken. Did you reload a model?

**Comment by geovedi** [comment]
no reload. just reuse embedding. 

just re-read the Press & Wolf paper again, i suspect that the embeddings i use are the problem. from the paper, "..., the input embedding is far inferior to the output embedding. The tied embedding is comparable to the output embedding."

will restart the training to set `embedding-fix-src: true` and `embedding-fix-trg: false` as the embedding-src was the output of previous model.

**Comment by geovedi** [comment]
i'll will test word2vec and glove embeddings later.

**Comment by emjotde** [comment]
Yes, I am testing with the same settings now and seeing improved convergence and better quality with w2v embeddings. At least this early into the training run.

**Comment by emjotde** [comment]
Just a follow-up. It seems that using `--tied-embeddings` is not a good idea for pre-computed embeddings. It converges faster in the beginning, but lacks behind later. So maybe remove that options from your set-up. Generally, using pre-computed embeddings with normalization seems to be beneficial in the long run.

**Comment by geovedi** [comment]
noted.
