### ISSUE TITLE
build error with Cudnn_6021 

### ISSUE THREAD

**Issue by geovedi** [marian-nmt/marian-train#72]
there's an error which broke my build (i'm using Cudnn_6021).

	xyz@xyz-01:~/workdir/src/marian-train$ git rev-parse --short HEAD
	93856ed

	xyz@xyz-01:~/workdir/src/marian-train/build$ cmake -DCOMPILE_TESTS=ON -DCOMPILE_EXAMPLES=ON ..
	-- The CXX compiler identification is GNU 5.4.0
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Looking for C++ include pthread.h
	-- Looking for C++ include pthread.h - found
	-- Looking for pthread_create
	-- Looking for pthread_create - not found
	-- Looking for pthread_create in pthreads
	-- Looking for pthread_create in pthreads - not found
	-- Looking for pthread_create in pthread
	-- Looking for pthread_create in pthread - found
	-- Found Threads: TRUE  
	-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "8.0") 
	-- Found CUDNN: /usr/local/cuda-8.0/include (Required is at least version "5.0") 
	-- Found Cudnn_6021 at /usr/local/cuda-8.0/include /usr/local/cuda-8.0/lib64/libcudnn.so
	-- Found ZLIB: .../anaconda3/lib/libz.so (found version "1.2.8") 
	-- Boost version: 1.58.0
	-- Found the following Boost libraries:
	--   system
	--   timer
	--   iostreams
	--   filesystem
	--   chrono
	--   program_options
	--   thread
	--   regex
	--   date_time
	--   atomic
	-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
	-- Configuring done
	-- Generating done
	-- Build files have been written to: .../workdir/src/marian-train/build

	xyz@xyz-01:~/workdir/src/marian-train/build$ make -j
	Scanning dependencies of target libyaml-cpp
	[  1%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/convert.cpp.o
	[  2%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/scanner.cpp.o
	[  3%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/emitfromevents.cpp.o
	[  4%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/exceptions.cpp.o
	[  6%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/node.cpp.o
	[  7%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/scantag.cpp.o
	[  8%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/scanscalar.cpp.o
	[  9%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/exp.cpp.o
	[ 12%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/emitter.cpp.o
	[ 12%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/emit.cpp.o
	[ 14%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/binary.cpp.o
	[ 17%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/node_data.cpp.o
	[ 13%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/ostream_wrapper.cpp.o
	[ 17%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/directives.cpp.o
	[ 28%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/contrib/graphbuilder.cpp.o
	[ 29%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/nodeevents.cpp.o
	[ 30%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/parse.cpp.o
	[ 31%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/nodebuilder.cpp.o
	[ 32%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/singledocparser.cpp.o
	[ 34%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/emitterutils.cpp.o
	[ 35%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/emitterstate.cpp.o
	[ 36%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/contrib/graphbuilderadapter.cpp.o
	[ 18%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/memory.cpp.o
	[ 19%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/null.cpp.o
	[ 20%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/parser.cpp.o
	[ 21%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/scantoken.cpp.o
	[ 23%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/stream.cpp.o
	[ 24%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/tag.cpp.o
	[ 26%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/simplekey.cpp.o
	[ 26%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/regex_yaml.cpp.o
	[ 36%] Built target libyaml-cpp
	[ 37%] Building NVCC (Device) object src/CMakeFiles/marian.dir/translator/marian_generated_helpers.cu.o
	[ 39%] Building NVCC (Device) object src/CMakeFiles/marian.dir/translator/marian_generated_nth_element.cu.o
	[ 40%] Building NVCC (Device) object src/CMakeFiles/marian.dir/graph/marian_generated_expression_operators.cu.o
	[ 41%] Building NVCC (Device) object src/CMakeFiles/marian.dir/graph/marian_generated_node.cu.o
	[ 43%] Building NVCC (Device) object src/CMakeFiles/marian.dir/layers/marian_generated_cells.cu.o
	[ 45%] Building NVCC (Device) object src/CMakeFiles/marian.dir/optimizers/marian_generated_optimizers.cu.o
	[ 42%] Building NVCC (Device) object src/CMakeFiles/marian.dir/graph/marian_generated_expression_graph.cu.o
	[ 46%] Building NVCC (Device) object src/CMakeFiles/marian.dir/kernels/marian_generated_tensor_operators.cu.o
	[ 47%] Building NVCC (Device) object src/CMakeFiles/marian.dir/graph/marian_generated_node_operators.cu.o
	[ 48%] Building NVCC (Device) object src/CMakeFiles/marian.dir/layers/marian_generated_attention.cu.o
	[ 50%] Building NVCC (Device) object src/CMakeFiles/marian.dir/kernels/marian_generated_sparse.cu.o
	[ 51%] Building NVCC (Device) object src/CMakeFiles/marian.dir/tensors/marian_generated_tensor.cu.o
	[ 52%] Building NVCC (Device) object src/CMakeFiles/marian.dir/optimizers/marian_generated_clippers.cu.o
	[ 53%] Building NVCC (Device) object src/CMakeFiles/marian.dir/kernels/marian_generated_dropout.cu.o
	.../workdir/src/marian-train/src/graph/node_operators_binary.h(429): error: too few arguments in function call

	.../workdir/src/marian-train/src/graph/node_operators_binary.h(429): error: too few arguments in function call

	.../workdir/src/marian-train/src/graph/node_operators_binary.h(429): error: too few arguments in function call

	.../workdir/src/marian-train/src/graph/node_operators_binary.h(429): error: too few arguments in function call

	.../workdir/src/marian-train/src/graph/node_operators_binary.h(429): error: too few arguments in function call

	.../workdir/src/marian-train/src/graph/node_operators_binary.h(429): error: too few arguments in function call

	2 errors detected in the compilation of "/tmp/tmpxft_00003a24_00000000-7_attention.cpp1.ii".
	2 errors detected in the compilation of "/tmp/tmpxft_00003a32_00000000-7_expression_operators.cpp1.ii".
	CMake Error at marian_generated_expression_operators.cu.o.cmake:262 (message):
	  Error generating file
	  .../workdir/src/marian-train/build/src/CMakeFiles/marian.dir/graph/./marian_generated_expression_operators.cu.o

	src/CMakeFiles/marian.dir/build.make:70: recipe for target 'src/CMakeFiles/marian.dir/graph/marian_generated_expression_operators.cu.o' failed
	make[2]: *** [src/CMakeFiles/marian.dir/graph/marian_generated_expression_operators.cu.o] Error 1
	make[2]: *** Waiting for unfinished jobs....
	CMake Error at marian_generated_attention.cu.o.cmake:262 (message):
	  Error generating file
	  .../workdir/src/marian-train/build/src/CMakeFiles/marian.dir/layers/./marian_generated_attention.cu.o

	src/CMakeFiles/marian.dir/build.make:119: recipe for target 'src/CMakeFiles/marian.dir/layers/marian_generated_attention.cu.o' failed
	make[2]: *** [src/CMakeFiles/marian.dir/layers/marian_generated_attention.cu.o] Error 1
	2 errors detected in the compilation of "/tmp/tmpxft_00003a3f_00000000-7_cells.cpp1.ii".
	CMake Error at marian_generated_cells.cu.o.cmake:262 (message):
	  Error generating file
	  .../workdir/src/marian-train/build/src/CMakeFiles/marian.dir/layers/./marian_generated_cells.cu.o

	src/CMakeFiles/marian.dir/build.make:126: recipe for target 'src/CMakeFiles/marian.dir/layers/marian_generated_cells.cu.o' failed
	make[2]: *** [src/CMakeFiles/marian.dir/layers/marian_generated_cells.cu.o] Error 1
	CMakeFiles/Makefile2:97: recipe for target 'src/CMakeFiles/marian.dir/all' failed
	make[1]: *** [src/CMakeFiles/marian.dir/all] Error 2
	Makefile:94: recipe for target 'all' failed
	make: *** [all] Error 2

**Comment by emjotde** [comment]
@tomekd can we make CuDNN optional per compiler flag?

**Comment by geovedi** [comment]
i managed to build with this workaround.

```diff
diff --git a/src/graph/node_operators_binary.h b/src/graph/node_operators_binary.h
index eda5a36..34d54f8 100644
--- a/src/graph/node_operators_binary.h
+++ b/src/graph/node_operators_binary.h
@@ -429,7 +429,7 @@ class ConvolutionOp : public NaryNodeOp {
       CUDNN_CALL( cudnnSetConvolution2dDescriptor(convDesc_,
                     heightPad, widthPad, heightStride, widthStride,
                     1, 1,  // upscales
-                    CUDNN_CROSS_CORRELATION
+                    CUDNN_CROSS_CORRELATION, CUDNN_DATA_FLOAT
       ));
 
       // std::cerr << "data: " << nodes[0]->shape() << std::endl;
```

**Comment by geovedi** [comment]
@tomekd i think this might fix the issue

```diff
diff --git a/src/graph/node_operators_binary.h b/src/graph/node_operators_binary.h
index eda5a36..cf83997 100644
--- a/src/graph/node_operators_binary.h
+++ b/src/graph/node_operators_binary.h
@@ -426,11 +426,19 @@ class ConvolutionOp : public NaryNodeOp {
       int widthStride = 1;
 
       CUDNN_CALL( cudnnCreateConvolutionDescriptor(&convDesc_) );
+#if CUDNN_MAJOR > 5
+      CUDNN_CALL( cudnnSetConvolution2dDescriptor(convDesc_,
+                    heightPad, widthPad, heightStride, widthStride,
+                    1, 1,  // upscales
+                    CUDNN_CROSS_CORRELATION, CUDNN_DATA_FLOAT
+      ));
+#else
       CUDNN_CALL( cudnnSetConvolution2dDescriptor(convDesc_,
                     heightPad, widthPad, heightStride, widthStride,
                     1, 1,  // upscales
                     CUDNN_CROSS_CORRELATION
       ));
+#endif
 
       // std::cerr << "data: " << nodes[0]->shape() << std::endl;
       // std::cerr << "filter: " << nodes[1]->shape() << std::endl;
```

**Comment by tomekd** [comment]
Thanks. I'll fix that asap.

**Comment by emjotde** [comment]
I disabled Cudnn for the moment. Causing to much problems.

**Comment by geovedi** [comment]
ok.

**Comment by emjotde** [comment]
Let's keep this open. It's not fixed, just temporarily disabled.

**Comment by emjotde** [comment]
@tomek It seems this issue is back with CUDNN=ON

**Comment by tomekd** [comment]
start working on that.

**Comment by tomekd** [comment]
Fixed: branch issue-72
@geovedi : can you confirm that the fix is working for you?

**Comment by geovedi** [comment]
yes, thank you!

**Comment by tomekd** [comment]
Fixed and merged.
