### ISSUE TITLE
Segmentation fault from logger in s2s and rescorer

### ISSUE THREAD

**Issue by snukky** [marian-nmt/marian-train#74]
Logging is not yet initialized in `addOptions`, so we get segmentation fault in s2s and rescorer from here: 2def3251add6af4d959db127bfd96cd1c1de90e6:

    0x0000000000444cbf in spdlog::details::line_logger 
        spdlog::logger::_log_if_enabled<>(spdlog::level::level_enum, char const*) ()

I temporally commented the logging, but a fix is needed.

Another thing: is "verbose" [here](https://github.com/marian-nmt/marian-train/blob/master/src/common/logging.cpp#L76) correct?

**Comment by emjotde** [comment]
What's going on with this one? Is the pull request still valid after the recent changes?
