### ISSUE TITLE
One big output matrix multiply per minibatch

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-train#76]
In the forward step, we currently do |sentence| multiplies of the form
|batch| x |hidden| times |hidden| x |vocab|
But the output matrix isn't needed to continue time steps, so we could just buffer up the hidden states (we need the activations in RAM anyway) and do one big
|sentence| x |batch| x |hidden| tensor times |hidden| x |vocab|
This came from a discussion with NVIDIA and supposes that larger matrix multiplies are generally faster.  

It's an instance of the more general autobatching.

**Comment by emjotde** [comment]
True, clever. 
I do however have models where the next step depends on the output, the hard attention models for instance.  Will take a look at that.

**Comment by emjotde** [comment]
Actually, after some thinking, I believe we are doing this already? During translation you need to do it per time step due to beam search. During training there is only one big multiply.

**Comment by emjotde** [comment]
Closing unless I am wrong.
