### ISSUE TITLE
All cudaMalloc calls should be wrapped in CUDA_CHECK

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-train#89]
Hey,

I was getting some weird behavior when using the gradient drop, when approaching the maximum GPU memory, but I ended up in an infinite loop in stead of crashing. A quick search in the code revealed a few locations where cudaMalloc is not wrapped in guards. Those should be fixed.

https://github.com/marian-nmt/marian-train/blob/master/src/training/sparse_tensor.h#L65
https://github.com/marian-nmt/marian-train/blob/master/src/kernels/sparse.h#L89
https://github.com/marian-nmt/marian-train/blob/master/src/training/dropper.h#L111

In addition to that, we seem to have two guards that do exactly the same. One of them (I guess the nth_element one, because it's less idiomatic) should go.
https://github.com/marian-nmt/marian-train/blob/master/src/translator/nth_element.cu#L7
and 
https://github.com/marian-nmt/marian-train/blob/master/src/kernels/cuda_helpers.h#L7

If you agree with that I can quickly fix that and do a pull request. (Or i can haz write access to repo?)

Cheers,

Nick

**Comment by emjotde** [comment]
You can haz, but there be dragons in these areas of code, so careful please.

**Comment by emjotde** [comment]
@afaji Alham, this seems to be mostly your gradient dropping stuff.

**Comment by XapaJIaMnu** [comment]
I promise to not edit commit before asking the authors.

**Comment by XapaJIaMnu** [comment]
Fixed by 588d317
